name: CarePackage
version: 1.0.1
author: Naruse
main: fr.naruse.carepackage.main.CarePackagePlugin
softdepend: [Vault, WorldEdit]
commands:
  cp:
    description: "CarePackage's commands"
    aliases: [carepackage]
